# Dynamo
dynamodb:
  image: peopleperhour/dynamodb
  container_name: dynamodb
  ports:
    - "8000:8000"

redis:
  image: redis:3.2.4
  container_name: redis
  ports:
    - "6379:6379"

#Mocks
mocks:
  build: ../mocks
  ports:
    - "8083:8083"
